import {
  Banknote,
  BriefcaseBusiness,
  CarFront,
  ChartNoAxesCombined,
  Clapperboard,
  Coffee,
  Dumbbell,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  MoreHorizontal,
  PackageOpen,
  PawPrint,
  PiggyBank,
  Plane,
  ReceiptText,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  Sparkles,
  Utensils,
  Wifi,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  salary: Banknote,
  bonus: Sparkles,
  food: Utensils,
  home: House,
  transport: CarFront,
  shopping: ShoppingBag,
  health: HeartPulse,
  education: GraduationCap,
  entertainment: Clapperboard,
  saving: PiggyBank,
  bill: ReceiptText,
  coffee: Coffee,
  grocery: ShoppingBasket,
  travel: Plane,
  pet: PawPrint,
  gift: Gift,
  sport: Dumbbell,
  insurance: ShieldCheck,
  internet: Wifi,
  work: BriefcaseBusiness,
  investment: ChartNoAxesCombined,
  other: MoreHorizontal,
};

export const CATEGORY_ICON_FALLBACK = PackageOpen;
